language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tslint typescript gulp
script: 
  - npm install --prefix ./frontend
  - gulp --cwd ./frontend clean
  - gulp --cwd ./frontend ts
  - gulp --cwd ./frontend sass
  - tslint frontend/src/**/*.ts{,x}