version: 0.0
os: linux
files:
  - source: /frontend
    destination: /home/ec2-user/deployment/
hooks:
  AfterInstall:
    - location: deployment_scripts/start_server
      timeout: 300
      runas: ec2-user