#!/bin/bash
rm -R -f /www/* &&
cd /home/ec2-user/deployment/ &&
sudo chown ec2-user * -R -f &&
npm install &&
npm install gulp -D &&
gulp clean &&
gulp ts &&
gulp sass &&
cp *.html /www/ &&
cp dist /www/ -R &&
cp img /www/ -R &&
cd /home/ec2-user/backend/ &&
sudo chown ec2-user * -R -f &&
npm install &&
forever stopall &&
forever start /home/ec2-user/backend/src/index.js