#!/bin/bash
cd /home/ec2-user &&
source .bash_profile &&
sudo chown ec2-user:ec2-user * -R -f &&
cd deployment &&
npm install &&
npm install gulp -D &&
gulp build-prod
cp *.html /www/ -f &&
cp dist /www/ -R -f &&
cp img /www/ -R -f &&
cd ~/backend/ &&
npm install &&
forever stopall &&
forever start /home/ec2-user/backend/src/index.js ~/ugram-config.json