#!/bin/bash
killall -s SIGKILL -I gulp &&
cd /www &&
npm install --unsafe-perm &&
npm install gulp -D &&
npm install gulp-cli -g &&
chmod -R 777 ./ &&
 /usr/local/sbin/daemonize -c /www /usr/bin/gulp smart-serve --port 80